// login-reactts/src/components/register/register.tsx
import * as React from 'react';
import { connect, ConnectedComponentClass } from 'react-redux';
import { AnyAction, bindActionCreators, Dispatch } from 'redux';
import { Link, Redirect } from 'react-router-dom';

import { Action } from '../../store/actions/action';
import { FormValidationRule } from '../../tform-validation-rule';
import { LoginActionPayload } from '../../store/actions/login/tlogin-action-payload';
import { FormField } from '../shared/form-field/form-field';
import { Header } from '../shared/header/header';
import { registerAction } from '../../store/actions/login/register-action';
import { LoginState } from '../../store/reducers/login-reducer';

import './styles.scss';

/**
 * Register error messages.
 * @property {string} firstName - first name field error message.
 * @property {string} lastName - last name field error message.
 * @property {string} email - email field error message.
 * @property {string} password - password field error message.
 * @property {string} confirmPassword - confirm password field error message.
 */
type RegisterErrorMessages = {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  confirmPassword: string;
};

/**
 * Field properties.
 * @property {string} label - field label caption.
 * @property {string} id - input field id.
 * @property {string} type - input field type (text or password).
 * @property {string} name- input field name.
 * @property {string} value - input field value.
 * @property {string} error - error feedback.
 */
type Field = {
  label: string,
  id: string,
  type: 'text' | 'password',
  name: string,
  value: string,
  error: string
};

/**
 * Props.
 * @property {registerAction} actions.register - register action.
 * @property {LoginState} login - login state.
 */
export type Props = {
  actions: {
    register: typeof registerAction
  },
  login: LoginState,
  validator: (validationRules: FormValidationRule[], values: any, errorMsgs: any) => boolean
};

/**
 * Component state.
 * @property {string} formValues.firstName - form first name input value.
 * @property {string} formValues.lastName - form last name input value.
 * @property {string} formValues.email - form email input value.
 * @property {string} formValues.password - form password input value.
 * @property {string} formValues.confirmPassword - form confirm password input value.
 * @property {RegisterErrorMessages} errors - form input errors.
 */
type State = {
  formValues: {
    firstName: string,
    lastName: string,
    email: string,
    password: string,
    confirmPassword: string
  },
  errors: RegisterErrorMessages
};

/**
 * Register component.
 */
export class RegisterComponent extends React.Component<Props, State> {
  // @member {State} state - component state.
  public state: State = {
    formValues: {
      firstName: '',
      lastName: '',
      email: '',
      password: '',
      confirmPassword: ''
    },
    errors: {
      firstName: '',
      lastName: '',
      email: '',
      password: '',
      confirmPassword: ''
    }
  };

  /**
   * Change input field value.
   * @param {React.ChangeEvent<HTMLInputElement>} event - event that fired change.
   */
  private changeInput: (event: React.ChangeEvent<HTMLInputElement>) => void = (event: React.ChangeEvent<HTMLInputElement>): void => {
    let fieldName: string = event.target.name;
    let value: string = event.target.value;
    this.setState((state: State) => ({
      formValues: {
        ...state.formValues,
        [fieldName]: value
      }
    }));
  };

  /**
   * Validate form values.
   * @return {RegisterErrorMessages | undefined} returns error messages for form or nothing if form values passes validation.
   */
  private validateForm(): RegisterErrorMessages | undefined {
    const errors: RegisterErrorMessages = {
      firstName: '',
      lastName: '',
      email: '',
      password: '',
      confirmPassword: ''
    };

    const validationRules: FormValidationRule[] = [{
      prop: 'firstName',
      error: 'Please enter a valid first name',
      validator: (value: string) => !!value
    }, {
      prop: 'lastName',
      error: 'Please enter a valid last name',
      validator: (value: string) => !!value
    }, {
      prop: 'email',
      error: 'Please enter a valid email address',
      validator: (value: string) => !!value && value.length > 3 && -1 !== value.indexOf('@')
    }, {
      prop: 'password',
      error: 'Please enter a valid password',
      validator: (value: string) => !!value
    }, {
      prop: 'password',
      error: 'Please use at least 6 characters',
      validator: (value: string) => value.length >= 6
    }, {
      prop: 'confirmPassword',
      error: 'Passwords must match',
      validator: (value: string) => value === this.state.formValues.password
    }];

    const passed: boolean = this.props.validator(validationRules, this.state.formValues, errors);
    return passed ? undefined : errors;
  }
  
  /**
   * Register a new user.
   */
  public register: (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => void =
    (event: React.MouseEvent<HTMLButtonElement, MouseEvent>): void => {
      event.preventDefault();

      // clear previous errors
      this.setState({
        errors: {
          firstName: '',
          lastName: '',
          email: '',
          password: '',
          confirmPassword: ''
        }
      });

      // validate form
      const errors: RegisterErrorMessages | undefined = this.validateForm();
      if (!errors) {
        // register
        this.props.actions.register(this.state.formValues.firstName,
          this.state.formValues.lastName,
          this.state.formValues.email,
          this.state.formValues.password
        );
      } else {
        // set errors
        this.setState({
          errors: errors
        });  
      }
    };

  /**
   * Render
   * @return {JSX.Element} component render.
   */
  public render(): JSX.Element {
    // form fields
    const fields: Field[] = [{
      label: 'First Name',
      id: 'first-name',
      type: 'text',
      name: 'firstName',
      value: this.state.formValues.firstName,
      error: this.state.errors.firstName
    }, {
      label: 'Last Name',
      id: 'last-name',
      type: 'text',
      name: 'lastName',
      value: this.state.formValues.lastName,
      error: this.state.errors.lastName
    }, {
      label: 'Email',
      id: 'email',
      type: 'text',
      name: 'email',
      value: this.state.formValues.email,
      error: this.state.errors.email
    }, {
      label: 'Password',
      id: 'password',
      type: 'password',
      name: 'password',
      value: this.state.formValues.password,
      error: this.state.errors.password
    }, {
      label: 'Confirm Password',
      id: 'confirm-password',
      type: 'password',
      name: 'confirmPassword',
      value: this.state.formValues.confirmPassword,
      error: this.state.errors.confirmPassword
    }];

    return (
      <>
        {this.props.login.token && <Redirect to="/"/>}
        <Header title="Register"/>
        <main className="form">
          <section className="form__block">
            <form>
              {
                fields.map((field: Field) => (
                  <FormField
                    key={ field.id}
                    id={ field.id }
                    label={ field.label }
                    type={ field.type }
                    name={ field.name }
                    value={ field.value }
                    changeInput={ this.changeInput }
                    error={ field.error }/>
                ))
              }
              <button onClick={this.register} className="btn btn--center btn--block">Register</button>
              <p className="form__field-error">{ this.props.login.error }</p>
              <Link to="/login" className="btn btn--center btn--block btn--form">Login</Link>
            </form>
          </section>
        </main>
      </>
    );
  }
}

// map store state to props
export const mapStateToProps: (state: {login: LoginState}) => {login: LoginState} = (state: {login: LoginState}) => ({
  login: state.login
});

// map store actions to props
export const mapDispatchToProps: (dispatch: Dispatch<AnyAction>) => {
  actions: {
    register: (firstName: string, lastName: string, email: string, password: string) =>
      (dispatch: (action: Action<LoginActionPayload>) => void) => Promise<any>
  }
} = (dispatch: Dispatch<AnyAction>) => ({
  actions: bindActionCreators({
    register: registerAction
  }, dispatch)
});

// connect component to store and export wrapper
export const Register: ConnectedComponentClass<typeof RegisterComponent, any> =
  connect(mapStateToProps, mapDispatchToProps)(RegisterComponent);

// login-angular/src/app/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { FormValidationRule } from '../core/form-services/form-validation-rule';
import { FormValidationService } from '../core/form-services/form-validation.service';
import { RegisterService } from '../core/register-services/register.service';

/**
 * Register error messages.
 * @property {string} firstName - error message for first name field.
 * @property {string} lastName - error message for last name field.
 * @property {string} email - error message for email field.
 * @property {string} password - error message for password field.
 * @property {string} confirmPassword - error message for confirm password field.
 * @property {string} register - error message for register attempt.
 */
interface RegisterErrorMessages {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  confirmPassword: string;
  register: string;
}

/**
 * Register form values.
 * @property {string} firstName - first name field value.
 * @property {string} lastName - last name field value.
 * @property {string} email - email field value.
 * @property {string} password - password field value.
 * @property {string} confirmPassword - confirm password field value.
 */
interface RegisterFormValues {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  confirmPassword: string;
}

/**
 * New user registration component.
 */
@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {
  // @member {RegisterErrorMessages} errors - error messages.
  public errors: RegisterErrorMessages = {
    firstName: '',
    lastName: '',
    email: '',
    password: '',
    confirmPassword: '',
    register: ''
  };

  // @member {RegisterFormValues} formValues - form values.
  public formValues: RegisterFormValues = {
    firstName: '',
    lastName: '',
    email: '',
    password: '',
    confirmPassword: ''
  };

  /**
   * Constructor.
   * @param {FormValidationService} formValidationService - form validation service provider.
   * @param {RegisterService} registerService - user register service provider.
   * @param {Router} router - router services provider.
   */
  constructor(private formValidationService: FormValidationService,
              private registerService: RegisterService,
              private router: Router) { }

  /**
   * On init lifecycle callback.
   */
  public ngOnInit(): void {}

  /**
   * Clear form validation errors.
   */
  private clearFormValidationErrors(): void {
    this.errors = {
      firstName: '',
      lastName: '',
      email: '',
      password: '',
      confirmPassword: '',
      register: ''
    };
  }

  /**
   * Validate form values.
   * @return {RegisterErrorMessages|void} returns error messages for form or nothing if form values passes validation.
   */
  private validateForm(): RegisterErrorMessages|void {
    const errors: RegisterErrorMessages = {
      firstName: '',
      lastName: '',
      email: '',
      password: '',
      confirmPassword: '',
      register: ''
    };

    const validationRules: FormValidationRule[] = [{
      prop: 'firstName',
      error: 'Please enter a valid first name',
      validator: value => value
    }, {
      prop: 'lastName',
      error: 'Please enter a valid last name',
      validator: value => value
    }, {
      prop: 'email',
      error: 'Please enter a valid email address',
      validator: value => value && value.length > 3 && -1 !== value.indexOf('@')
    }, {
      prop: 'password',
      error: 'Please enter a valid password',
      validator: value => value
    }, {
      prop: 'password',
      error: 'Please use at least 6 characters',
      validator: value => value.length >= 6
    }, {
      prop: 'confirmPassword',
      error: 'Passwords must match',
      validator: value => value === this.formValues.password
    }];

    const passed: boolean = this.formValidationService.validator(validationRules, this.formValues, errors);
    return passed ? undefined : errors;
  }

  /**
   * Register action.
   * @param {Event} event - click event.
   */
  public register(event: Event): void {
    event.preventDefault();

    const errors = this.validateForm();
    if (!errors) {
      this.clearFormValidationErrors();

      const {firstName, lastName, email, password} = this.formValues;
      this.registerService.register(firstName, lastName, email, password)
        .subscribe(success => {
          if (success) {
            this.router.navigate(['/']);
          } else {
            // display register failed
            this.errors.register = 'Please try again';
          }
        }, () => {
          // display register failed
          this.errors.register = 'Please check your connection and try again';
        });
    } else {
      this.errors = errors;
    }
  }
}

<header>
  <h1 class="header">Register</h1>
</header>

<main class="form">
  <section class="form__block">
    <form>
      <label class="form__field" for="first-name">First Name
        <input [(ngModel)]="formValues.firstName" class="form__input" id="first-name" type="text" name="firstName">
        <p class="form__field-error">{{ errors.firstName }}</p>
      </label>
      <label class="form__field" for="last-name">Last Name
        <input [(ngModel)]="formValues.lastName" class="form__input" id="last-name" type="text" name="lastName">
        <p class="form__field-error">{{ errors.lastName }}</p>
      </label>
      <label class="form__field" for="email">Email
        <input [(ngModel)]="formValues.email" class="form__input" id="email" type="text" name="email">
        <p class="form__field-error">{{ errors.email }}</p>
      </label>
      <label class="form__field" for="password">Password
        <input [(ngModel)]="formValues.password" class="form__input" id="password" type="password" name="password">
        <p class="form__field-error">{{ errors.password }}</p>
      </label>
      <label class="form__field" for="confirm-password">Confirm Password
        <input [(ngModel)]="formValues.confirmPassword" class="form__input" id="confirm-password" type="password" name="confirmPassword">
        <p class="form__field-error">{{ errors.confirmPassword }}</p>
      </label>
      <button (click)="register($event)" class="btn btn--center btn--block">Register</button>
      <p class="form__field-error">{{ errors.register }}</p>
      <a routerLink="/login" class="btn btn--center btn--block btn--form">Login</a>
    </form>
  </section>
</main>
